title: D&D Characters
description: My D&D character collection and planning resources
theme: midnight
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-sitemap

# Build settings
exclude:
  - "*.pdf"